-- ============================================================
-- JHARKHAND SOCIETAL INNOVATION COLLABORATION PORTAL
-- Database Seed — Phase 1
-- Run AFTER schema.sql in Supabase SQL Editor
-- ============================================================

-- ============================================================
-- DOMAIN KEYWORDS SEED
-- 10 domains × initial keyword sets for AI classification
-- ============================================================

INSERT INTO domain_keywords (domain, keyword, weight) VALUES

-- ── EDUCATION ──────────────────────────────────────────────
('Education', 'school',             1.5),
('Education', 'student',            1.5),
('Education', 'teacher',            1.4),
('Education', 'literacy',           1.4),
('Education', 'dropout',            1.6),
('Education', 'classroom',          1.3),
('Education', 'curriculum',         1.3),
('Education', 'learning',           1.2),
('Education', 'mid-day meal',       1.4),
('Education', 'enrollment',         1.5),
('Education', 'anganwadi',          1.4),
('Education', 'primary education',  1.6),
('Education', 'higher education',   1.5),
('Education', 'scholarship',        1.3),
('Education', 'digital learning',   1.3),
('Education', 'vocational',         1.2),
('Education', 'coaching',           1.1),
('Education', 'college',            1.3),
('Education', 'university',         1.2),
('Education', 'skill development',  1.3),

-- ── AGRICULTURE ────────────────────────────────────────────
('Agriculture', 'farm',             1.5),
('Agriculture', 'farmer',           1.6),
('Agriculture', 'crop',             1.5),
('Agriculture', 'irrigation',       1.6),
('Agriculture', 'drought',          1.6),
('Agriculture', 'soil',             1.4),
('Agriculture', 'fertilizer',       1.3),
('Agriculture', 'pesticide',        1.3),
('Agriculture', 'harvest',          1.4),
('Agriculture', 'kisan',            1.5),
('Agriculture', 'seed',             1.3),
('Agriculture', 'msp',              1.4),
('Agriculture', 'yield',            1.3),
('Agriculture', 'land',             1.2),
('Agriculture', 'storage',          1.2),
('Agriculture', 'cold storage',     1.4),
('Agriculture', 'mandi',            1.4),
('Agriculture', 'tribal farming',   1.5),
('Agriculture', 'forest produce',   1.4),
('Agriculture', 'jhum cultivation', 1.5),

-- ── HEALTHCARE ─────────────────────────────────────────────
('Healthcare', 'hospital',          1.5),
('Healthcare', 'health',            1.4),
('Healthcare', 'doctor',            1.5),
('Healthcare', 'medicine',          1.4),
('Healthcare', 'malaria',           1.6),
('Healthcare', 'tuberculosis',      1.6),
('Healthcare', 'maternal',          1.5),
('Healthcare', 'child mortality',   1.7),
('Healthcare', 'nutrition',         1.4),
('Healthcare', 'anemia',            1.5),
('Healthcare', 'PHC',               1.5),
('Healthcare', 'ASHA',              1.4),
('Healthcare', 'ambulance',         1.4),
('Healthcare', 'vaccination',       1.4),
('Healthcare', 'sanitation',        1.3),
('Healthcare', 'hygiene',           1.3),
('Healthcare', 'mental health',     1.5),
('Healthcare', 'epidemic',          1.6),
('Healthcare', 'sickle cell',       1.6),
('Healthcare', 'ayushman',          1.3),

-- ── WATER RESOURCES ────────────────────────────────────────
('Water Resources', 'water',        1.5),
('Water Resources', 'drinking water',1.7),
('Water Resources', 'bore well',    1.5),
('Water Resources', 'hand pump',    1.5),
('Water Resources', 'pipeline',     1.4),
('Water Resources', 'dam',          1.4),
('Water Resources', 'river',        1.3),
('Water Resources', 'flood',        1.6),
('Water Resources', 'waterlogging', 1.5),
('Water Resources', 'scarcity',     1.5),
('Water Resources', 'contamination',1.6),
('Water Resources', 'groundwater',  1.5),
('Water Resources', 'watershed',    1.4),
('Water Resources', 'pond',         1.3),
('Water Resources', 'tank',         1.3),
('Water Resources', 'rainwater',    1.4),
('Water Resources', 'tap water',    1.5),
('Water Resources', 'jal jeevan',   1.5),
('Water Resources', 'arsenic',      1.6),
('Water Resources', 'fluoride',     1.6),

-- ── ENVIRONMENT ────────────────────────────────────────────
('Environment', 'pollution',        1.6),
('Environment', 'forest',           1.5),
('Environment', 'deforestation',    1.6),
('Environment', 'wildlife',         1.4),
('Environment', 'mining',           1.5),
('Environment', 'air quality',      1.5),
('Environment', 'waste',            1.4),
('Environment', 'garbage',          1.4),
('Environment', 'plastic',          1.3),
('Environment', 'climate',          1.4),
('Environment', 'temperature',      1.3),
('Environment', 'biodiversity',     1.4),
('Environment', 'green cover',      1.4),
('Environment', 'effluent',         1.5),
('Environment', 'solid waste',      1.4),
('Environment', 'e-waste',          1.4),
('Environment', 'noise pollution',  1.3),
('Environment', 'coal',             1.4),
('Environment', 'illegal mining',   1.6),
('Environment', 'encroachment',     1.4),

-- ── ENERGY ─────────────────────────────────────────────────
('Energy', 'electricity',           1.6),
('Energy', 'power',                 1.4),
('Energy', 'solar',                 1.5),
('Energy', 'load shedding',         1.6),
('Energy', 'grid',                  1.3),
('Energy', 'voltage',               1.4),
('Energy', 'transformer',           1.4),
('Energy', 'kerosene',              1.4),
('Energy', 'LPG',                   1.4),
('Energy', 'biomass',               1.4),
('Energy', 'renewable',             1.4),
('Energy', 'off-grid',              1.5),
('Energy', 'streetlight',           1.4),
('Energy', 'outage',                1.5),
('Energy', 'meter',                 1.3),
('Energy', 'electrification',       1.6),
('Energy', 'saubhagya',             1.5),
('Energy', 'photovoltaic',          1.4),
('Energy', 'energy access',         1.6),
('Energy', 'cooking fuel',          1.4),

-- ── URBAN DEVELOPMENT ──────────────────────────────────────
('Urban Development', 'road',       1.5),
('Urban Development', 'pothole',    1.5),
('Urban Development', 'drainage',   1.5),
('Urban Development', 'housing',    1.4),
('Urban Development', 'slum',       1.5),
('Urban Development', 'traffic',    1.4),
('Urban Development', 'footpath',   1.3),
('Urban Development', 'street light',1.4),
('Urban Development', 'park',       1.2),
('Urban Development', 'market',     1.2),
('Urban Development', 'bus stand',  1.4),
('Urban Development', 'municipality',1.3),
('Urban Development', 'smart city', 1.4),
('Urban Development', 'pavement',   1.3),
('Urban Development', 'encroachment',1.4),
('Urban Development', 'construction',1.2),
('Urban Development', 'bridge',     1.4),
('Urban Development', 'urban planning',1.4),
('Urban Development', 'building',   1.2),
('Urban Development', 'public toilet',1.5),

-- ── ACCESSIBILITY ──────────────────────────────────────────
('Accessibility', 'disability',     1.7),
('Accessibility', 'wheelchair',     1.6),
('Accessibility', 'ramp',           1.5),
('Accessibility', 'blind',          1.6),
('Accessibility', 'deaf',           1.6),
('Accessibility', 'divyang',        1.7),
('Accessibility', 'barrier',        1.5),
('Accessibility', 'inclusive',      1.4),
('Accessibility', 'accessible',     1.5),
('Accessibility', 'braille',        1.5),
('Accessibility', 'sign language',  1.5),
('Accessibility', 'assistive',      1.5),
('Accessibility', 'specially abled',1.6),
('Accessibility', 'mobility',       1.4),
('Accessibility', 'transport',      1.3),
('Accessibility', 'elevator',       1.4),
('Accessibility', 'toilet facility',1.4),
('Accessibility', 'UDID',           1.4),
('Accessibility', 'rehabilitation', 1.5),
('Accessibility', 'prosthetic',     1.5),

-- ── PUBLIC ADMINISTRATION ──────────────────────────────────
('Public Administration', 'corruption',     1.7),
('Public Administration', 'bribery',        1.7),
('Public Administration', 'government scheme',1.5),
('Public Administration', 'ration',         1.5),
('Public Administration', 'PDS',            1.5),
('Public Administration', 'certificate',    1.4),
('Public Administration', 'caste certificate',1.5),
('Public Administration', 'land record',    1.5),
('Public Administration', 'panchayat',      1.4),
('Public Administration', 'block office',   1.4),
('Public Administration', 'police',         1.3),
('Public Administration', 'FIR',            1.4),
('Public Administration', 'pension',        1.4),
('Public Administration', 'welfare',        1.3),
('Public Administration', 'subsidy',        1.4),
('Public Administration', 'grievance',      1.5),
('Public Administration', 'transparency',   1.4),
('Public Administration', 'digitization',   1.3),
('Public Administration', 'e-governance',   1.4),
('Public Administration', 'delay',          1.3),

-- ── RURAL LIVELIHOODS ──────────────────────────────────────
('Rural Livelihoods', 'livelihood',         1.6),
('Rural Livelihoods', 'employment',         1.5),
('Rural Livelihoods', 'MGNREGA',            1.6),
('Rural Livelihoods', 'SHG',                1.5),
('Rural Livelihoods', 'self help group',    1.5),
('Rural Livelihoods', 'income',             1.4),
('Rural Livelihoods', 'poverty',            1.5),
('Rural Livelihoods', 'tribal',             1.5),
('Rural Livelihoods', 'adivasi',            1.5),
('Rural Livelihoods', 'migration',          1.6),
('Rural Livelihoods', 'crafts',             1.4),
('Rural Livelihoods', 'handloom',           1.4),
('Rural Livelihoods', 'micro enterprise',   1.4),
('Rural Livelihoods', 'market access',      1.4),
('Rural Livelihoods', 'value chain',        1.3),
('Rural Livelihoods', 'tendu',              1.4),
('Rural Livelihoods', 'minor forest',       1.4),
('Rural Livelihoods', 'van dhan',           1.5),
('Rural Livelihoods', 'cooperative',        1.4),
('Rural Livelihoods', 'JSLPS',              1.5)

ON CONFLICT (domain, keyword) DO UPDATE
  SET weight = EXCLUDED.weight,
      updated_at = now();
